version: '3.7'

networks:
  answers-network:
    driver: bridge

volumes:
  mongo_db_data:

services:
  answers:
    build:
      context: .
    environment:
      LOG_LEVEL: DEBUG
      MONGODB_URI: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@db:27017
    command: --host 0.0.0.0 --port 8080
    networks:
      - answers-network
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    networks:
        - answers-network
    ports:
      - 27017:27017
    volumes:
      - mongo_db_data:/data/db

  db-ui:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_UI_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_UI_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
    networks:
      - answers-network
    ports:
      - 8081:8081
    volumes:
      - mongo_db_data:/data/db
    depends_on:
      - db
